### PR TITLE
Update ItemPreview.js

### PR DESCRIPTION
**Pull request by Octax557**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @Octax557, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by Octax557 — COMMENTED** [review]
Capture d’écran 2022-08-08 à 12 10 06

**Pull request closed without merging**
